#!/bin/bash
#

set AUDIODEV=hw:1

DECODER=wsprcan/k9an-wsprd
TMPOUT='_wsprd.out'

echo "run loopback"
pactl load-module module-loopback source=alsa_input.platform-4010000000.pcie-pci-0000_00_02.0.analog-stereo

echo "run i2c"
cd /home/elec3607/ELEC3607/lab3-i2c/
./Si5351

decode () {
	date
	cd /home/elec3607/ELEC3607/lab5-audio/wsprcan/
	./k9an-wsprd >> /home/elec3607/ELEC3607/lab5-audio/wsproutput.log

	sleep 110
}

while true
do
	sec=$(date +'%S')
	min=$(date +'%M')
	# wait for an even minute
	if (("10#$min" % 2 == 0 && "10#$sec" == 0 )); then
		echo -n "Executing wspr_decode "
		decode
	elif ((10#$sec < 49)); then
		sleep 10
	fi
done
